# Inserts a blank line between shell prompts
add_newline = false

format = """
[╭](blue) $username@$hostname [.=](red) [$directory]($git_branch$git_state$git_status)
[╰─](blue)$git_branch[─> ](blue)"""

[directory]
style = "cyan"
truncate_to_repo = false
read_only = " (read-only)"
fish_style_pwd_dir_length = 1

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "purple"

[username]
show_always = true
style_user = "blue"
format = "[$user]($style)"

[git_branch]
style = "green"
format = "[\\[[$branch$tag](cyan)\\]](white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[status]
style = "red"
format = '[\[$status \($common_meaning/$signal_name\)$maybe_int\]]($style) '
disabled = false
