# Author: RayGervais<raygervais@hotmail.ca>
# Author: ChrisHa<chunghha@users.noreply.github.com>
# Author: GreasySlug <9619abgoni@gmail.com>
# Author: marceline-cramer<cramermarceline@gmail.com>

# Cursor + cursorline
"ui.cursor" = { fg = "rose", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "highlightHigh" }
"ui.cursor.primary" = { modifiers = ["reversed", "slow_blink"] }
"ui.cursor.secondary" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "surface" }
"ui.cursorline.secondary" = { bg = "surface" }

# Code and command completion menus
"ui.menu" = { fg = "subtle", bg = "overlay" }
"ui.menu.selected" = { fg = "base", bg = "foam" }

# Line numbers + virtual UI
"ui.linenr" = { fg = "muted" }
"ui.linenr.selected" = { fg = "text", modifiers = ["bold"] }
"ui.virtual.indent-guide" = "muted"
"ui.virtual.ruler" = { bg = "surface" }
"ui.virtual.whitespace" = "muted"

# Status line
"ui.statusline" = { fg = "subtle", bg = "surface" }
"ui.statusline.inactive"= { fg = "base", bg = "surface" }
"ui.statusline.normal"  = { fg = "base", bg = "iris", modifiers = ["bold"] }
"ui.statusline.insert"  = { fg = "base", bg = "pine", modifiers = ["bold"] }
"ui.statusline.select"  = { fg = "base", bg = "rose", modifiers = ["bold"] }

# Text
"ui.text" = "text"
"ui.text.focus" = { fg = "text", bg = "highlightHigh", modifiers = ["bold"] }
"ui.text.info" = "pine"
"ui.selection" = { bg = "highlightMed" }

# Misc. UI
"ui.background" = { }
"ui.popup" = { fg = "text", bg = "overlay" }
"ui.window" = { fg = "text", bg = "surface" }
"ui.help" = { fg = "text", bg = "overlay" }

# Syntax highlighting
"attribute" = "yellow"
"comment" = { fg = "gray", modifiers = ["italic"] }
"constant" = "yellow"
"constant.character.escape" = "cyan"
"constant.numeric" = "yellow"
"constructor" = "blue"
"function" = "blue"
"keyword" = "magenta"
"label" = "magenta"
"namespace" = "magenta"
"punctuation" = "text"
"special" = "cyan"
"string"  = "green"
"type" = "yellow"
"variable" = "cyan"
"variable.builtin" = "magenta"
"variable.other.member" = "green"

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "green"
"markup.normal" = { fg = "blue" }
"markup.insert" = { fg = "green" }
"markup.select" = { fg = "magenta" }

"diff.plus" = "light-green"
"diff.delta" = "yellow"
"diff.minus" = "light-red"

# Gutter
"ui.gutter" = "subtle"
"info" = "gold"
"hint" = "foam"
"debug" = "pine"
"warning" = "rose"
"error" = "love"

# Diagnostics (editing area)
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.info"    = { fg = "gold", modifiers = ["underlined"] }
"diagnostic.hint"    = { fg = "foam", modifiers = ["underlined"] }
"diagnostic.debug"   = { fg = "pine", modifiers = ["underlined"] }
"diagnostic.warning" = { fg = "rose", modifiers = ["underlined"] }
"diagnostic.error"   = { fg = "love", modifiers = ["underlined"] }

[palette]
base     = "#191724" 
surface  = "#1f1d2e" 
overlay  = "#26233a"
inactive = "#555169"
subtle   = "#908caa"
muted    = "#6e6a86"
text     = "#e0def4"
love     = "#eb6f92"
gold     = "#f6c177"
rose     = "#ebbcba"
pine     = "#31748f"
foam     = "#9ccfd8"
iris     = "#c4a7e7"
highlightLow      = "#21202e"
highlightMed      = "#403d52"
highlightHigh     = "#524f67"
highlightInactive = "#211f2d"
highlightOverlay  = "#3a384a"
